#!/usr/bin/env python3
"""Generate the proxy export stubs for a system DLL.

Reads the export address table of the real DLL (no external dependencies -
the PE headers are parsed by hand) and writes a C++ translation unit with one
PROXY_STUB(<name>) per named export, suitable for compiling the mod as a
proxy for that DLL. Ordinal-only exports additionally get a PROXY_ORDINAL_STUB
plus an entry in the generated .def file that exports them under the same
ordinal.

Usage: gen_proxy.py <system dll path> <output .cpp> <output .def>

Aborts if the DLL has forwarded exports - GetProcAddress is not guaranteed to
resolve a forwarder, so those would need explicit handling.
"""

import re
import struct
import sys

IDENT = re.compile(rb"[A-Za-z_][A-Za-z0-9_]*")


def u16(d, o):
    return struct.unpack_from("<H", d, o)[0]


def u32(d, o):
    return struct.unpack_from("<I", d, o)[0]


def fail(msg):
    sys.exit("gen_proxy.py: %s" % msg)


def parse_exports(path):
    d = open(path, "rb").read()
    if d[:2] != b"MZ":
        fail("%s: not a PE file (missing MZ)" % path)
    pe = u32(d, 0x3C)
    if d[pe : pe + 4] != b"PE\0\0":
        fail("%s: not a PE file (missing PE signature)" % path)
    opt = pe + 24
    magic = u16(d, opt)
    if magic == 0x20B:
        dd_base = opt + 112  # PE32+
    elif magic == 0x10B:
        dd_base = opt + 96   # PE32
    else:
        fail("%s: unknown optional header magic 0x%X" % (path, magic))
    exp_rva, exp_size = u32(d, dd_base), u32(d, dd_base + 4)
    if not exp_rva:
        fail("%s: DLL has no export table" % path)

    nsects = u16(d, pe + 6)
    sect_off = opt + u16(d, pe + 20)
    sections = []
    for i in range(nsects):
        s = sect_off + 40 * i
        sections.append((u32(d, s + 12), u32(d, s + 8), u32(d, s + 20), u32(d, s + 16)))

    def rva_to_off(rva):
        for va, vsz, raw, rsz in sections:
            if va <= rva < va + max(vsz, rsz):
                return raw + (rva - va)
        return None

    def is_forwarded(func_rva):
        return exp_rva <= func_rva < exp_rva + exp_size

    eo = rva_to_off(exp_rva)
    if eo is None:
        fail("%s: export directory RVA 0x%X not mapped" % (path, exp_rva))

    n_funcs = u32(d, eo + 20)
    n_names = u32(d, eo + 24)
    ordinal_base = u32(d, eo + 16)
    funcs = rva_to_off(u32(d, eo + 28))
    names = rva_to_off(u32(d, eo + 32))
    ords = rva_to_off(u32(d, eo + 36))

    named = {}
    for i in range(n_names):
        noff = rva_to_off(u32(d, names + 4 * i))
        name = d[noff : d.index(b"\0", noff)]
        ordinal_idx = u16(d, ords + 2 * i)
        func_rva = u32(d, funcs + 4 * ordinal_idx)
        # Same name can appear more than once in the name table; keep the
        # first occurrence (they all point at the same function).
        if name not in named:
            named[name] = (ordinal_base + ordinal_idx, is_forwarded(func_rva))

    used = {u16(d, ords + 2 * i) for i in range(n_names)}
    ordinal_only = [
        (ordinal_base + i, is_forwarded(u32(d, funcs + 4 * i)))
        for i in range(n_funcs)
        if i not in used
    ]
    return list(named.items()), ordinal_only


def main():
    if len(sys.argv) != 4:
        fail("usage: gen_proxy.py <system dll path> <output .cpp> <output .def>")
    dll_path, out_cpp, out_def = sys.argv[1], sys.argv[2], sys.argv[3]

    named, ordinal_only = parse_exports(dll_path)

    bad = [n for n, (o, fwd) in named if fwd or not IDENT.fullmatch(n)]
    bad_ord = [o for o, fwd in ordinal_only if fwd]
    if bad or bad_ord:
        for n in bad:
            print("  unsupported named export: %s" % n.decode("ascii", "replace"), file=sys.stderr)
        for o in bad_ord:
            print("  unsupported forwarded ordinal export: @%d" % o, file=sys.stderr)
        fail(
            "%s has %d named, %d forwarded ordinal exports that PROXY_STUB cannot "
            "handle; add explicit stubs for them or pick another proxy target"
            % (dll_path, len(bad), len(bad_ord))
        )

    lines = [
        "// Auto-generated by tools/gen_proxy.py from %s - do not edit." % dll_path,
        "#include \"proxy.h\"",
        "",
    ]
    lines += ["PROXY_STUB(%s)" % n.decode("ascii") for n, _ in named]
    lines += ["PROXY_ORDINAL_STUB(%d)" % o for o, _ in ordinal_only]
    lines.append("")
    with open(out_cpp, "w", newline="\n") as f:
        f.write("\n".join(lines))

    # Every export gets its real ordinal so the proxy's export table is a
    # full mirror of the original (ordinal importers keep working).
    def_lines = [
        "; Auto-generated by tools/gen_proxy.py from %s - do not edit." % dll_path,
        "; Named stubs are defined as ProxyStub_<name> and exported under the",
        "; real export name (system headers declare the real prototypes, so the",
        "; exported names cannot be defined directly in C).",
        "EXPORTS",
    ]
    def_lines += [
        "%s=ProxyStub_%s @%d" % (n.decode("ascii"), n.decode("ascii"), o)
        for n, (o, _) in named
    ]
    def_lines += [
        "ProxyOrdinal_%d @%d NONAME" % (o, o) for o, _ in ordinal_only
    ]
    with open(out_def, "w", newline="\n") as f:
        f.write("\n".join(def_lines) + "\n")

    print(
        "gen_proxy.py: %d named, %d ordinal stubs -> %s, %s"
        % (len(named), len(ordinal_only), out_cpp, out_def)
    )


if __name__ == "__main__":
    main()
